name: Deploy branch previews to GitHub Pages

on:
  push:
    branches:
      - main
      - history
      - test   # add more branches as needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build per-branch folders
        run: |
          mkdir -p site

          # Branches you want deployed
          BRANCHES="main test"

          for BR in $BRANCHES; do
            echo "Building preview for branch: $BR"
            mkdir -p "site/$BR"

            git ls-tree -r --name-only "$BR" | while read file; do
              mkdir -p "site/$BR/$(dirname "$file")"
              git show "$BR:$file" > "site/$BR/$file"
            done
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
